name: Update Devspaces Link to match Branch
on: [push, fork]
jobs:
  update-manifests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3  
      - run: |
          export BRANCH=$(git rev-parse --abbrev-ref HEAD)
          export REPO="${{ github.server_url }}/${{ github.repository }}"
          
          sed -i "s:\[\!\[Edit this Branch\]\(.*\)\]\(.*\)\/tree\/.*:[![Edit this Branch]\1]\2/tree/$BRANCH?new):g" ./README.md

          if [ $( git status --porcelain | head -255 | wc -l ) -ne 0 ]
          then 
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Automated action to make manifests match branch"
            git push
          else
            exit 0
          fi